services:
  - type: web
    name: lab5-lavalust
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /login
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
      - key: DB_SSL_CA
        sync: false
      - key: DB_SSL_CA_BASE64
        sync: false
      - key: ADMIN_USERNAME
        value: Administrator
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
